feat(cli): Dirk multi-node delegation support
chainbound/bolt pull request #509
Opened 2024-12-02 17:45 UTC by merklefruit

This PR adds support for creating signed delegations from multi-node Dirk instances (aka `DistributedAccount`).

Unfortunately, the BLS library we have used until now (`BLST`) doesn't support M-N threshold signature recovery.
See the related issue: https://github.com/supranational/blst/issues/123

Since this operation is not overly complex, I've decided to implement it manually in `recover_signature.rs`,
following the [C reference implementation in MCL](https://github.com/herumi/mcl/blob/328e26f45ba565d031f9570e68e3d61836a17d7c/include/mcl/lagrange.hpp#L16) directly.

The implementation is tested by generating a signed delegation against a 2-of-3 Dirk setup running locally and then verifying the signature against the combined public key.

2024-12-02 17:54 UTC, merklefruit commented on bolt-cli/src/commands/delegate/dirk.rs
> +    async fn test_delegation_dirk_multi() -> eyre::Result<()> {
this is WIP.

2024-12-03 09:40 UTC, thedevbirb approved these changes
Great job. BLS is so cool

2024-12-03 09:40 UTC, thedevbirb commented on bolt-cli/src/common/dirk/distributed.rs
> +            // TODO: might have to unlock the account here
Is this stale?

2024-12-03 09:45 UTC, mempirate commented on bolt-cli/src/commands/delegate/dirk.rs
> +    async fn test_delegation_dirk_single() -> eyre::Result<()> {
Very nice tests

2024-12-03 10:12 UTC, mempirate requested changes

2024-12-03 10:12 UTC, mempirate commented on bolt-cli/src/common/dirk/distributed.rs
> +            };
Can we do this concurrently by pushing them into a `FuturesUnordered` or something similar for each participant?

2024-12-03 10:12 UTC, mempirate commented on bolt-cli/src/common/dirk/test_util.rs
> +    let test_data_dir = env!("CARGO_MANIFEST_DIR").to_string() + "/test_data/dirk_single";
Nit but can use `concat!(env!("CARGO_MANIFEST_DIR"), "/test_data/dirk_single");

2024-12-03 10:16 UTC, merklefruit commented on bolt-cli/src/common/dirk/distributed.rs
> +            // TODO: might have to unlock the account here
Yes, removing

2024-12-03 10:23 UTC, merklefruit commented on bolt-cli/src/common/dirk/test_util.rs
> +    let test_data_dir = env!("CARGO_MANIFEST_DIR").to_string() + "/test_data/dirk_single";
nice, done

2024-12-03 10:24 UTC, merklefruit commented on bolt-cli/src/common/dirk/distributed.rs
> +            };
Yes but it would need to be throttled to avoid DDoSing dirk

2024-12-03 10:44 UTC, merklefruit commented on bolt-cli/src/common/dirk/distributed.rs
> +            };
done

2024-12-03 10:52 UTC, mempirate approved these changes
LGTM! Great work

2024-12-03 10:53 UTC, merged